ALTER TABLE repo ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE repo ADD COLUMN tech_stack TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE repo ADD COLUMN setup_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE repo ADD COLUMN has_code BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE repo ADD COLUMN has_claude_md BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE repo ADD COLUMN has_readme BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE repo ADD COLUMN expectations TEXT NOT NULL DEFAULT '';
ALTER TABLE repo ADD COLUMN setup_completed_at BIGINT;
