// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package sqlc

import (
	"context"
)

const claimConversation = `-- name: ClaimConversation :execrows
UPDATE conversation SET
  claimed_at = unixepoch(),
  last_heartbeat_at = unixepoch(),
  updated_at = unixepoch()
WHERE id = ? AND status = 'active' AND pending_message IS NOT NULL AND claimed_at IS NULL
`

func (q *Queries) ClaimConversation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimConversation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const conversationHeartbeat = `-- name: ConversationHeartbeat :exec
UPDATE conversation SET
  last_heartbeat_at = unixepoch(),
  updated_at = unixepoch()
WHERE id = ?
`

func (q *Queries) ConversationHeartbeat(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, conversationHeartbeat, id)
	return err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversation (id, repo_id, title, status, messages, model, pending_message, epic_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID             string
	RepoID         string
	Title          string
	Status         string
	Messages       string
	Model          *string
	PendingMessage *string
	EpicID         *string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.RepoID,
		arg.Title,
		arg.Status,
		arg.Messages,
		arg.Model,
		arg.PendingMessage,
		arg.EpicID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversation WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const listActiveConversations = `-- name: ListActiveConversations :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation
WHERE status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveConversations(ctx context.Context) ([]*Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByRepo = `-- name: ListConversationsByRepo :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation WHERE repo_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByRepo(ctx context.Context, repoID string) ([]*Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingConversations = `-- name: ListPendingConversations :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation
WHERE status = 'active' AND pending_message IS NOT NULL AND claimed_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPendingConversations(ctx context.Context) ([]*Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleConversations = `-- name: ListStaleConversations :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation
WHERE claimed_at IS NOT NULL
  AND last_heartbeat_at < ?
  AND status = 'active'
ORDER BY last_heartbeat_at ASC
`

func (q *Queries) ListStaleConversations(ctx context.Context, lastHeartbeatAt *int64) ([]*Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listStaleConversations, lastHeartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readConversation = `-- name: ReadConversation :one
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation WHERE id = ?
`

func (q *Queries) ReadConversation(ctx context.Context, id string) (*Conversation, error) {
	row := q.db.QueryRowContext(ctx, readConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Title,
		&i.Status,
		&i.Messages,
		&i.Model,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.PendingMessage,
		&i.EpicID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const releaseConversationClaim = `-- name: ReleaseConversationClaim :exec
UPDATE conversation SET
  claimed_at = NULL,
  last_heartbeat_at = NULL,
  updated_at = unixepoch()
WHERE id = ?
`

func (q *Queries) ReleaseConversationClaim(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseConversationClaim, id)
	return err
}

const setConversationEpicID = `-- name: SetConversationEpicID :exec
UPDATE conversation SET epic_id = ?, updated_at = unixepoch()
WHERE id = ?
`

type SetConversationEpicIDParams struct {
	EpicID *string
	ID     string
}

func (q *Queries) SetConversationEpicID(ctx context.Context, arg SetConversationEpicIDParams) error {
	_, err := q.db.ExecContext(ctx, setConversationEpicID, arg.EpicID, arg.ID)
	return err
}

const setConversationMessages = `-- name: SetConversationMessages :exec
UPDATE conversation SET messages = ?, updated_at = unixepoch()
WHERE id = ?
`

type SetConversationMessagesParams struct {
	Messages string
	ID       string
}

func (q *Queries) SetConversationMessages(ctx context.Context, arg SetConversationMessagesParams) error {
	_, err := q.db.ExecContext(ctx, setConversationMessages, arg.Messages, arg.ID)
	return err
}

const setPendingMessage = `-- name: SetPendingMessage :exec
UPDATE conversation SET pending_message = ?, updated_at = unixepoch()
WHERE id = ?
`

type SetPendingMessageParams struct {
	PendingMessage *string
	ID             string
}

func (q *Queries) SetPendingMessage(ctx context.Context, arg SetPendingMessageParams) error {
	_, err := q.db.ExecContext(ctx, setPendingMessage, arg.PendingMessage, arg.ID)
	return err
}

const updateConversationStatus = `-- name: UpdateConversationStatus :exec
UPDATE conversation SET status = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateConversationStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationStatus, arg.Status, arg.ID)
	return err
}
