// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Epic struct {
	ID              string
	RepoID          string
	Title           string
	Description     string
	Status          string
	ProposedTasks   string
	TaskIds         string
	PlanningPrompt  *string
	SessionLog      string
	NotReady        int64
	ClaimedAt       *int64
	LastHeartbeatAt *int64
	Feedback        *string
	FeedbackType    *string
	Model           *string
	CreatedAt       int64
	UpdatedAt       int64
}

type GithubToken struct {
	ID             string
	EncryptedToken string
	CreatedAt      int64
	UpdatedAt      int64
}

type Repo struct {
	ID        string
	Owner     string
	Name      string
	FullName  string
	CreatedAt int64
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt int64
}

type Task struct {
	ID                     string
	RepoID                 string
	Title                  string
	Description            string
	Status                 string
	PullRequestUrl         *string
	PrNumber               *int64
	DependsOn              string
	CloseReason            *string
	Attempt                int64
	MaxAttempts            int64
	RetryReason            *string
	AcceptanceCriteriaList string
	AgentStatus            *string
	RetryContext           *string
	ConsecutiveFailures    int64
	CostUsd                float64
	MaxCostUsd             *float64
	SkipPr                 int64
	BranchName             *string
	Model                  *string
	StartedAt              *int64
	Ready                  int64
	LastHeartbeatAt        *int64
	EpicID                 *string
	CreatedAt              int64
	UpdatedAt              int64
}

type TaskLog struct {
	ID        int64
	TaskID    string
	Lines     string
	Attempt   int64
	CreatedAt int64
}
