// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo.sql

package sqlc

import (
	"context"
)

const createRepo = `-- name: CreateRepo :exec
INSERT INTO repo (id, owner, name, full_name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateRepoParams struct {
	ID        string
	Owner     string
	Name      string
	FullName  string
	CreatedAt int64
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) error {
	_, err := q.db.ExecContext(ctx, createRepo,
		arg.ID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.CreatedAt,
	)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repo WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const listRepos = `-- name: ListRepos :many
SELECT id, owner, name, full_name, created_at FROM repo ORDER BY created_at DESC
`

func (q *Queries) ListRepos(ctx context.Context) ([]*Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRepo = `-- name: ReadRepo :one
SELECT id, owner, name, full_name, created_at FROM repo WHERE id = ?
`

func (q *Queries) ReadRepo(ctx context.Context, id string) (*Repo, error) {
	row := q.db.QueryRowContext(ctx, readRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.CreatedAt,
	)
	return &i, err
}

const readRepoByFullName = `-- name: ReadRepoByFullName :one
SELECT id, owner, name, full_name, created_at FROM repo WHERE full_name = ?
`

func (q *Queries) ReadRepoByFullName(ctx context.Context, fullName string) (*Repo, error) {
	row := q.db.QueryRowContext(ctx, readRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.CreatedAt,
	)
	return &i, err
}
