// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo.sql

package sqlc

import (
	"context"
)

const createRepo = `-- name: CreateRepo :exec
INSERT INTO repo (id, owner, name, full_name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateRepoParams struct {
	ID        string
	Owner     string
	Name      string
	FullName  string
	CreatedAt int64
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) error {
	_, err := q.db.ExecContext(ctx, createRepo,
		arg.ID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.CreatedAt,
	)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repo WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const listRepos = `-- name: ListRepos :many
SELECT id, owner, name, full_name, created_at, summary, tech_stack, setup_status, has_code, has_claude_md, has_readme, expectations, setup_completed_at FROM repo ORDER BY created_at DESC
`

func (q *Queries) ListRepos(ctx context.Context) ([]*Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.CreatedAt,
			&i.Summary,
			&i.TechStack,
			&i.SetupStatus,
			&i.HasCode,
			&i.HasClaudeMd,
			&i.HasReadme,
			&i.Expectations,
			&i.SetupCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposBySetupStatus = `-- name: ListReposBySetupStatus :many
SELECT id, owner, name, full_name, created_at, summary, tech_stack, setup_status, has_code, has_claude_md, has_readme, expectations, setup_completed_at FROM repo WHERE setup_status = ? ORDER BY created_at DESC
`

func (q *Queries) ListReposBySetupStatus(ctx context.Context, setupStatus string) ([]*Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposBySetupStatus, setupStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.CreatedAt,
			&i.Summary,
			&i.TechStack,
			&i.SetupStatus,
			&i.HasCode,
			&i.HasClaudeMd,
			&i.HasReadme,
			&i.Expectations,
			&i.SetupCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRepo = `-- name: ReadRepo :one
SELECT id, owner, name, full_name, created_at, summary, tech_stack, setup_status, has_code, has_claude_md, has_readme, expectations, setup_completed_at FROM repo WHERE id = ?
`

func (q *Queries) ReadRepo(ctx context.Context, id string) (*Repo, error) {
	row := q.db.QueryRowContext(ctx, readRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.CreatedAt,
		&i.Summary,
		&i.TechStack,
		&i.SetupStatus,
		&i.HasCode,
		&i.HasClaudeMd,
		&i.HasReadme,
		&i.Expectations,
		&i.SetupCompletedAt,
	)
	return &i, err
}

const readRepoByFullName = `-- name: ReadRepoByFullName :one
SELECT id, owner, name, full_name, created_at, summary, tech_stack, setup_status, has_code, has_claude_md, has_readme, expectations, setup_completed_at FROM repo WHERE full_name = ?
`

func (q *Queries) ReadRepoByFullName(ctx context.Context, fullName string) (*Repo, error) {
	row := q.db.QueryRowContext(ctx, readRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.CreatedAt,
		&i.Summary,
		&i.TechStack,
		&i.SetupStatus,
		&i.HasCode,
		&i.HasClaudeMd,
		&i.HasReadme,
		&i.Expectations,
		&i.SetupCompletedAt,
	)
	return &i, err
}

const updateRepoExpectations = `-- name: UpdateRepoExpectations :exec
UPDATE repo
SET expectations = ?,
    setup_completed_at = ?
WHERE id = ?
`

type UpdateRepoExpectationsParams struct {
	Expectations     string
	SetupCompletedAt *int64
	ID               string
}

func (q *Queries) UpdateRepoExpectations(ctx context.Context, arg UpdateRepoExpectationsParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoExpectations, arg.Expectations, arg.SetupCompletedAt, arg.ID)
	return err
}

const updateRepoSetupScan = `-- name: UpdateRepoSetupScan :exec
UPDATE repo
SET summary = ?,
    tech_stack = ?,
    has_code = ?,
    has_claude_md = ?,
    has_readme = ?,
    setup_status = ?
WHERE id = ?
`

type UpdateRepoSetupScanParams struct {
	Summary     string
	TechStack   string
	HasCode     int64
	HasClaudeMd int64
	HasReadme   int64
	SetupStatus string
	ID          string
}

func (q *Queries) UpdateRepoSetupScan(ctx context.Context, arg UpdateRepoSetupScanParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoSetupScan,
		arg.Summary,
		arg.TechStack,
		arg.HasCode,
		arg.HasClaudeMd,
		arg.HasReadme,
		arg.SetupStatus,
		arg.ID,
	)
	return err
}

const updateRepoSetupStatus = `-- name: UpdateRepoSetupStatus :exec
UPDATE repo
SET setup_status = ?
WHERE id = ?
`

type UpdateRepoSetupStatusParams struct {
	SetupStatus string
	ID          string
}

func (q *Queries) UpdateRepoSetupStatus(ctx context.Context, arg UpdateRepoSetupStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoSetupStatus, arg.SetupStatus, arg.ID)
	return err
}

const updateRepoSummary = `-- name: UpdateRepoSummary :exec
UPDATE repo
SET summary = ?
WHERE id = ?
`

type UpdateRepoSummaryParams struct {
	Summary string
	ID      string
}

func (q *Queries) UpdateRepoSummary(ctx context.Context, arg UpdateRepoSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoSummary, arg.Summary, arg.ID)
	return err
}

const updateRepoTechStack = `-- name: UpdateRepoTechStack :exec
UPDATE repo
SET tech_stack = ?
WHERE id = ?
`

type UpdateRepoTechStackParams struct {
	TechStack string
	ID        string
}

func (q *Queries) UpdateRepoTechStack(ctx context.Context, arg UpdateRepoTechStackParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoTechStack, arg.TechStack, arg.ID)
	return err
}
