// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"
)

const addTaskCost = `-- name: AddTaskCost :exec
UPDATE task SET cost_usd = cost_usd + ?, updated_at = unixepoch() WHERE id = ?
`

type AddTaskCostParams struct {
	CostUsd float64
	ID      string
}

func (q *Queries) AddTaskCost(ctx context.Context, arg AddTaskCostParams) error {
	_, err := q.db.ExecContext(ctx, addTaskCost, arg.CostUsd, arg.ID)
	return err
}

const appendTaskLogs = `-- name: AppendTaskLogs :exec
INSERT INTO task_log (task_id, attempt, lines) VALUES (?, ?, ?)
`

type AppendTaskLogsParams struct {
	TaskID  string
	Attempt int64
	Lines   string
}

func (q *Queries) AppendTaskLogs(ctx context.Context, arg AppendTaskLogsParams) error {
	_, err := q.db.ExecContext(ctx, appendTaskLogs, arg.TaskID, arg.Attempt, arg.Lines)
	return err
}

const bulkCloseTasksByEpic = `-- name: BulkCloseTasksByEpic :exec
UPDATE task SET status = 'closed', close_reason = ?, updated_at = unixepoch()
WHERE epic_id = ? AND status NOT IN ('closed', 'merged')
`

type BulkCloseTasksByEpicParams struct {
	CloseReason *string
	EpicID      *string
}

func (q *Queries) BulkCloseTasksByEpic(ctx context.Context, arg BulkCloseTasksByEpicParams) error {
	_, err := q.db.ExecContext(ctx, bulkCloseTasksByEpic, arg.CloseReason, arg.EpicID)
	return err
}

const bulkDeleteTaskLogsByEpic = `-- name: BulkDeleteTaskLogsByEpic :exec
DELETE FROM task_log WHERE task_id IN (SELECT id FROM task WHERE epic_id = ?)
`

func (q *Queries) BulkDeleteTaskLogsByEpic(ctx context.Context, epicID *string) error {
	_, err := q.db.ExecContext(ctx, bulkDeleteTaskLogsByEpic, epicID)
	return err
}

const bulkDeleteTasksByEpic = `-- name: BulkDeleteTasksByEpic :exec
DELETE FROM task WHERE epic_id = ?
`

func (q *Queries) BulkDeleteTasksByEpic(ctx context.Context, epicID *string) error {
	_, err := q.db.ExecContext(ctx, bulkDeleteTasksByEpic, epicID)
	return err
}

const claimTask = `-- name: ClaimTask :execrows
UPDATE task SET status = 'running', started_at = unixepoch(), updated_at = unixepoch()
WHERE id = ? AND status = 'pending' AND ready = 1
`

func (q *Queries) ClaimTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearEpicIDForTasks = `-- name: ClearEpicIDForTasks :exec
UPDATE task SET epic_id = NULL, updated_at = unixepoch()
WHERE epic_id = ?
`

func (q *Queries) ClearEpicIDForTasks(ctx context.Context, epicID *string) error {
	_, err := q.db.ExecContext(ctx, clearEpicIDForTasks, epicID)
	return err
}

const closeTask = `-- name: CloseTask :exec
UPDATE task SET status = 'closed', close_reason = ?, updated_at = unixepoch()
WHERE id = ?
`

type CloseTaskParams struct {
	CloseReason *string
	ID          string
}

func (q *Queries) CloseTask(ctx context.Context, arg CloseTaskParams) error {
	_, err := q.db.ExecContext(ctx, closeTask, arg.CloseReason, arg.ID)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO task (id, repo_id, title, description, status, depends_on, attempt, max_attempts, acceptance_criteria_list, max_cost_usd, skip_pr, draft_pr, model, ready, epic_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID                     string
	RepoID                 string
	Title                  string
	Description            string
	Status                 string
	DependsOn              string
	Attempt                int64
	MaxAttempts            int64
	AcceptanceCriteriaList string
	MaxCostUsd             *float64
	SkipPr                 int64
	DraftPr                int64
	Model                  *string
	Ready                  int64
	EpicID                 *string
	CreatedAt              int64
	UpdatedAt              int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.RepoID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.DependsOn,
		arg.Attempt,
		arg.MaxAttempts,
		arg.AcceptanceCriteriaList,
		arg.MaxCostUsd,
		arg.SkipPr,
		arg.DraftPr,
		arg.Model,
		arg.Ready,
		arg.EpicID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredLogs = `-- name: DeleteExpiredLogs :execrows
DELETE FROM task_log WHERE created_at < ?
`

func (q *Queries) DeleteExpiredLogs(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredLogs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteTaskLogs = `-- name: DeleteTaskLogs :exec
DELETE FROM task_log WHERE task_id = ?
`

func (q *Queries) DeleteTaskLogs(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskLogs, taskID)
	return err
}

const feedbackRetryTask = `-- name: FeedbackRetryTask :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1,
  max_attempts = max_attempts + 1,
  retry_reason = ?, retry_context = NULL,
  consecutive_failures = 0,
  started_at = NULL, updated_at = unixepoch()
WHERE id = ? AND status = 'review'
`

type FeedbackRetryTaskParams struct {
	RetryReason *string
	ID          string
}

func (q *Queries) FeedbackRetryTask(ctx context.Context, arg FeedbackRetryTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, feedbackRetryTask, arg.RetryReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const hasTasksForRepo = `-- name: HasTasksForRepo :one
SELECT EXISTS(SELECT 1 FROM task WHERE repo_id = ?)
`

func (q *Queries) HasTasksForRepo(ctx context.Context, repoID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasTasksForRepo, repoID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const heartbeat = `-- name: Heartbeat :execrows
UPDATE task SET last_heartbeat_at = unixepoch() WHERE id = ? AND status = 'running'
`

func (q *Queries) Heartbeat(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'pending' AND ready = 1 ORDER BY created_at ASC
`

func (q *Queries) ListPendingTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleTasks = `-- name: ListStaleTasks :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'running' AND last_heartbeat_at IS NOT NULL AND last_heartbeat_at < ? ORDER BY started_at
`

func (q *Queries) ListStaleTasks(ctx context.Context, lastHeartbeatAt *int64) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listStaleTasks, lastHeartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByEpic = `-- name: ListTasksByEpic :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE epic_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListTasksByEpic(ctx context.Context, epicID *string) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByEpic, epicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByRepo = `-- name: ListTasksByRepo :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE repo_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTasksByRepo(ctx context.Context, repoID string) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInReview = `-- name: ListTasksInReview :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'review'
`

func (q *Queries) ListTasksInReview(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksInReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInReviewByRepo = `-- name: ListTasksInReviewByRepo :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE repo_id = ? AND status = 'review'
`

func (q *Queries) ListTasksInReviewByRepo(ctx context.Context, repoID string) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksInReviewByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInReviewNoPR = `-- name: ListTasksInReviewNoPR :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'review' AND branch_name IS NOT NULL AND pr_number IS NULL
`

func (q *Queries) ListTasksInReviewNoPR(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksInReviewNoPR)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.DraftPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manualRetryTask = `-- name: ManualRetryTask :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1,
  retry_reason = ?, retry_context = NULL,
  close_reason = NULL, consecutive_failures = 0,
  started_at = NULL, updated_at = unixepoch()
WHERE id = ? AND status = 'failed'
`

type ManualRetryTaskParams struct {
	RetryReason *string
	ID          string
}

func (q *Queries) ManualRetryTask(ctx context.Context, arg ManualRetryTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, manualRetryTask, arg.RetryReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readTask = `-- name: ReadTask :one
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, draft_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE id = ?
`

func (q *Queries) ReadTask(ctx context.Context, id string) (*Task, error) {
	row := q.db.QueryRowContext(ctx, readTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.PullRequestUrl,
		&i.PrNumber,
		&i.DependsOn,
		&i.CloseReason,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryReason,
		&i.AcceptanceCriteriaList,
		&i.AgentStatus,
		&i.RetryContext,
		&i.ConsecutiveFailures,
		&i.CostUsd,
		&i.MaxCostUsd,
		&i.SkipPr,
		&i.DraftPr,
		&i.BranchName,
		&i.Model,
		&i.StartedAt,
		&i.Ready,
		&i.LastHeartbeatAt,
		&i.EpicID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const readTaskLogs = `-- name: ReadTaskLogs :many
SELECT attempt, lines FROM task_log WHERE task_id = ? ORDER BY id
`

type ReadTaskLogsRow struct {
	Attempt int64
	Lines   string
}

func (q *Queries) ReadTaskLogs(ctx context.Context, taskID string) ([]*ReadTaskLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, readTaskLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReadTaskLogsRow
	for rows.Next() {
		var i ReadTaskLogsRow
		if err := rows.Scan(&i.Attempt, &i.Lines); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readTaskStatus = `-- name: ReadTaskStatus :one
SELECT status FROM task WHERE id = ?
`

func (q *Queries) ReadTaskStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, readTaskStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const retryTask = `-- name: RetryTask :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1, retry_reason = ?, started_at = NULL, updated_at = unixepoch()
WHERE id = ? AND status = 'review'
`

type RetryTaskParams struct {
	RetryReason *string
	ID          string
}

func (q *Queries) RetryTask(ctx context.Context, arg RetryTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryTask, arg.RetryReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const scheduleRetryFromRunning = `-- name: ScheduleRetryFromRunning :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1, retry_reason = ?, started_at = NULL, updated_at = unixepoch()
WHERE id = ? AND status = 'running'
`

type ScheduleRetryFromRunningParams struct {
	RetryReason *string
	ID          string
}

func (q *Queries) ScheduleRetryFromRunning(ctx context.Context, arg ScheduleRetryFromRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, scheduleRetryFromRunning, arg.RetryReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentStatus = `-- name: SetAgentStatus :exec
UPDATE task SET agent_status = ?, updated_at = unixepoch() WHERE id = ?
`

type SetAgentStatusParams struct {
	AgentStatus *string
	ID          string
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAgentStatus, arg.AgentStatus, arg.ID)
	return err
}

const setBranchName = `-- name: SetBranchName :exec
UPDATE task SET branch_name = ?, status = 'review', updated_at = unixepoch() WHERE id = ?
`

type SetBranchNameParams struct {
	BranchName *string
	ID         string
}

func (q *Queries) SetBranchName(ctx context.Context, arg SetBranchNameParams) error {
	_, err := q.db.ExecContext(ctx, setBranchName, arg.BranchName, arg.ID)
	return err
}

const setCloseReason = `-- name: SetCloseReason :exec
UPDATE task SET close_reason = ?, updated_at = unixepoch() WHERE id = ?
`

type SetCloseReasonParams struct {
	CloseReason *string
	ID          string
}

func (q *Queries) SetCloseReason(ctx context.Context, arg SetCloseReasonParams) error {
	_, err := q.db.ExecContext(ctx, setCloseReason, arg.CloseReason, arg.ID)
	return err
}

const setConsecutiveFailures = `-- name: SetConsecutiveFailures :exec
UPDATE task SET consecutive_failures = ?, updated_at = unixepoch() WHERE id = ?
`

type SetConsecutiveFailuresParams struct {
	ConsecutiveFailures int64
	ID                  string
}

func (q *Queries) SetConsecutiveFailures(ctx context.Context, arg SetConsecutiveFailuresParams) error {
	_, err := q.db.ExecContext(ctx, setConsecutiveFailures, arg.ConsecutiveFailures, arg.ID)
	return err
}

const setDependsOn = `-- name: SetDependsOn :exec
UPDATE task SET depends_on = ?, updated_at = unixepoch()
WHERE id = ?
`

type SetDependsOnParams struct {
	DependsOn string
	ID        string
}

func (q *Queries) SetDependsOn(ctx context.Context, arg SetDependsOnParams) error {
	_, err := q.db.ExecContext(ctx, setDependsOn, arg.DependsOn, arg.ID)
	return err
}

const setReady = `-- name: SetReady :exec
UPDATE task SET ready = ?, updated_at = unixepoch()
WHERE id = ?
`

type SetReadyParams struct {
	Ready int64
	ID    string
}

func (q *Queries) SetReady(ctx context.Context, arg SetReadyParams) error {
	_, err := q.db.ExecContext(ctx, setReady, arg.Ready, arg.ID)
	return err
}

const setRetryContext = `-- name: SetRetryContext :exec
UPDATE task SET retry_context = ?, updated_at = unixepoch() WHERE id = ?
`

type SetRetryContextParams struct {
	RetryContext *string
	ID           string
}

func (q *Queries) SetRetryContext(ctx context.Context, arg SetRetryContextParams) error {
	_, err := q.db.ExecContext(ctx, setRetryContext, arg.RetryContext, arg.ID)
	return err
}

const setTaskPullRequest = `-- name: SetTaskPullRequest :exec
UPDATE task SET pull_request_url = ?, pr_number = ?, status = 'review', updated_at = unixepoch()
WHERE id = ?
`

type SetTaskPullRequestParams struct {
	PullRequestUrl *string
	PrNumber       *int64
	ID             string
}

func (q *Queries) SetTaskPullRequest(ctx context.Context, arg SetTaskPullRequestParams) error {
	_, err := q.db.ExecContext(ctx, setTaskPullRequest, arg.PullRequestUrl, arg.PrNumber, arg.ID)
	return err
}

const startOverTask = `-- name: StartOverTask :execrows
UPDATE task SET
  status = 'pending',
  title = ?,
  description = ?,
  acceptance_criteria_list = ?,
  attempt = 1,
  max_attempts = 5,
  retry_reason = NULL,
  retry_context = NULL,
  close_reason = NULL,
  agent_status = NULL,
  consecutive_failures = 0,
  cost_usd = 0,
  pull_request_url = NULL,
  pr_number = NULL,
  branch_name = NULL,
  started_at = NULL,
  updated_at = unixepoch()
WHERE id = ? AND status IN ('review', 'failed', 'closed')
`

type StartOverTaskParams struct {
	Title                  string
	Description            string
	AcceptanceCriteriaList string
	ID                     string
}

func (q *Queries) StartOverTask(ctx context.Context, arg StartOverTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startOverTask,
		arg.Title,
		arg.Description,
		arg.AcceptanceCriteriaList,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stopTask = `-- name: StopTask :execrows
UPDATE task SET status = 'pending', ready = 0, close_reason = ?,
  started_at = NULL, updated_at = unixepoch()
WHERE id = ? AND status = 'running'
`

type StopTaskParams struct {
	CloseReason *string
	ID          string
}

func (q *Queries) StopTask(ctx context.Context, arg StopTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stopTask, arg.CloseReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS(SELECT 1 FROM task WHERE id = ?)
`

func (q *Queries) TaskExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, taskExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePendingTask = `-- name: UpdatePendingTask :execrows
UPDATE task SET
  title = ?,
  description = ?,
  depends_on = ?,
  acceptance_criteria_list = ?,
  max_cost_usd = ?,
  skip_pr = ?,
  draft_pr = ?,
  model = ?,
  ready = ?,
  updated_at = unixepoch()
WHERE id = ? AND status = 'pending'
`

type UpdatePendingTaskParams struct {
	Title                  string
	Description            string
	DependsOn              string
	AcceptanceCriteriaList string
	MaxCostUsd             *float64
	SkipPr                 int64
	DraftPr                int64
	Model                  *string
	Ready                  int64
	ID                     string
}

func (q *Queries) UpdatePendingTask(ctx context.Context, arg UpdatePendingTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePendingTask,
		arg.Title,
		arg.Description,
		arg.DependsOn,
		arg.AcceptanceCriteriaList,
		arg.MaxCostUsd,
		arg.SkipPr,
		arg.DraftPr,
		arg.Model,
		arg.Ready,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task SET status = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
