ALTER TABLE repo ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE repo ADD COLUMN tech_stack TEXT NOT NULL DEFAULT '[]';
ALTER TABLE repo ADD COLUMN setup_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE repo ADD COLUMN has_code INTEGER NOT NULL DEFAULT 0;
ALTER TABLE repo ADD COLUMN has_claude_md INTEGER NOT NULL DEFAULT 0;
ALTER TABLE repo ADD COLUMN has_readme INTEGER NOT NULL DEFAULT 0;
ALTER TABLE repo ADD COLUMN expectations TEXT NOT NULL DEFAULT '';
ALTER TABLE repo ADD COLUMN setup_completed_at INTEGER;
