// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package sqlc

import (
	"context"
)

const appendConversationMessage = `-- name: AppendConversationMessage :exec
UPDATE conversation SET messages = messages || $2::jsonb, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type AppendConversationMessageParams struct {
	ID      string `json:"id"`
	Column2 []byte `json:"column_2"`
}

func (q *Queries) AppendConversationMessage(ctx context.Context, arg AppendConversationMessageParams) error {
	_, err := q.db.Exec(ctx, appendConversationMessage, arg.ID, arg.Column2)
	return err
}

const claimConversation = `-- name: ClaimConversation :execrows
UPDATE conversation SET
  claimed_at = EXTRACT(EPOCH FROM NOW())::BIGINT,
  last_heartbeat_at = EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'active' AND pending_message IS NOT NULL AND claimed_at IS NULL
`

func (q *Queries) ClaimConversation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, claimConversation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const conversationHeartbeat = `-- name: ConversationHeartbeat :exec
UPDATE conversation SET
  last_heartbeat_at = EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

func (q *Queries) ConversationHeartbeat(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, conversationHeartbeat, id)
	return err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversation (id, repo_id, title, status, messages, model, pending_message, epic_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateConversationParams struct {
	ID             string  `json:"id"`
	RepoID         string  `json:"repo_id"`
	Title          string  `json:"title"`
	Status         string  `json:"status"`
	Messages       []byte  `json:"messages"`
	Model          *string `json:"model"`
	PendingMessage *string `json:"pending_message"`
	EpicID         *string `json:"epic_id"`
	CreatedAt      int64   `json:"created_at"`
	UpdatedAt      int64   `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.Exec(ctx, createConversation,
		arg.ID,
		arg.RepoID,
		arg.Title,
		arg.Status,
		arg.Messages,
		arg.Model,
		arg.PendingMessage,
		arg.EpicID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversation WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const listActiveConversations = `-- name: ListActiveConversations :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation
WHERE status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveConversations(ctx context.Context) ([]*Conversation, error) {
	rows, err := q.db.Query(ctx, listActiveConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByRepo = `-- name: ListConversationsByRepo :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation WHERE repo_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByRepo(ctx context.Context, repoID string) ([]*Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingConversations = `-- name: ListPendingConversations :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation
WHERE status = 'active' AND pending_message IS NOT NULL AND claimed_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPendingConversations(ctx context.Context) ([]*Conversation, error) {
	rows, err := q.db.Query(ctx, listPendingConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleConversations = `-- name: ListStaleConversations :many
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation
WHERE claimed_at IS NOT NULL
  AND last_heartbeat_at < $1
  AND status = 'active'
ORDER BY last_heartbeat_at ASC
`

func (q *Queries) ListStaleConversations(ctx context.Context, lastHeartbeatAt *int64) ([]*Conversation, error) {
	rows, err := q.db.Query(ctx, listStaleConversations, lastHeartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Status,
			&i.Messages,
			&i.Model,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.PendingMessage,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readConversation = `-- name: ReadConversation :one
SELECT id, repo_id, title, status, messages, model, claimed_at, last_heartbeat_at, pending_message, epic_id, created_at, updated_at FROM conversation WHERE id = $1
`

func (q *Queries) ReadConversation(ctx context.Context, id string) (*Conversation, error) {
	row := q.db.QueryRow(ctx, readConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Title,
		&i.Status,
		&i.Messages,
		&i.Model,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.PendingMessage,
		&i.EpicID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const releaseConversationClaim = `-- name: ReleaseConversationClaim :exec
UPDATE conversation SET
  claimed_at = NULL,
  last_heartbeat_at = NULL,
  updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

func (q *Queries) ReleaseConversationClaim(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, releaseConversationClaim, id)
	return err
}

const setConversationEpicID = `-- name: SetConversationEpicID :exec
UPDATE conversation SET epic_id = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type SetConversationEpicIDParams struct {
	ID     string  `json:"id"`
	EpicID *string `json:"epic_id"`
}

func (q *Queries) SetConversationEpicID(ctx context.Context, arg SetConversationEpicIDParams) error {
	_, err := q.db.Exec(ctx, setConversationEpicID, arg.ID, arg.EpicID)
	return err
}

const setConversationMessages = `-- name: SetConversationMessages :exec
UPDATE conversation SET messages = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type SetConversationMessagesParams struct {
	ID       string `json:"id"`
	Messages []byte `json:"messages"`
}

func (q *Queries) SetConversationMessages(ctx context.Context, arg SetConversationMessagesParams) error {
	_, err := q.db.Exec(ctx, setConversationMessages, arg.ID, arg.Messages)
	return err
}

const setPendingMessage = `-- name: SetPendingMessage :exec
UPDATE conversation SET pending_message = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type SetPendingMessageParams struct {
	ID             string  `json:"id"`
	PendingMessage *string `json:"pending_message"`
}

func (q *Queries) SetPendingMessage(ctx context.Context, arg SetPendingMessageParams) error {
	_, err := q.db.Exec(ctx, setPendingMessage, arg.ID, arg.PendingMessage)
	return err
}

const updateConversationStatus = `-- name: UpdateConversationStatus :exec
UPDATE conversation SET status = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type UpdateConversationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error {
	_, err := q.db.Exec(ctx, updateConversationStatus, arg.ID, arg.Status)
	return err
}
