// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_token.sql

package sqlc

import (
	"context"
)

const deleteGitHubToken = `-- name: DeleteGitHubToken :exec
DELETE FROM github_token WHERE id = 'default'
`

func (q *Queries) DeleteGitHubToken(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteGitHubToken)
	return err
}

const readGitHubToken = `-- name: ReadGitHubToken :one
SELECT encrypted_token FROM github_token WHERE id = 'default'
`

func (q *Queries) ReadGitHubToken(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, readGitHubToken)
	var encrypted_token string
	err := row.Scan(&encrypted_token)
	return encrypted_token, err
}

const upsertGitHubToken = `-- name: UpsertGitHubToken :exec
INSERT INTO github_token (id, encrypted_token, created_at, updated_at)
VALUES ('default', $1, $2, $2)
ON CONFLICT (id) DO UPDATE SET encrypted_token = $1, updated_at = $2
`

type UpsertGitHubTokenParams struct {
	EncryptedToken string `json:"encrypted_token"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) UpsertGitHubToken(ctx context.Context, arg UpsertGitHubTokenParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubToken, arg.EncryptedToken, arg.CreatedAt)
	return err
}
