// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
)

type TaskStatus string

const (
	TaskStatusPending TaskStatus = "pending"
	TaskStatusRunning TaskStatus = "running"
	TaskStatusReview  TaskStatus = "review"
	TaskStatusMerged  TaskStatus = "merged"
	TaskStatusClosed  TaskStatus = "closed"
	TaskStatusFailed  TaskStatus = "failed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusPending,
		TaskStatusRunning,
		TaskStatusReview,
		TaskStatusMerged,
		TaskStatusClosed,
		TaskStatusFailed:
		return true
	}
	return false
}

func AllTaskStatusValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusPending,
		TaskStatusRunning,
		TaskStatusReview,
		TaskStatusMerged,
		TaskStatusClosed,
		TaskStatusFailed,
	}
}

type Conversation struct {
	ID              string  `json:"id"`
	RepoID          string  `json:"repo_id"`
	Title           string  `json:"title"`
	Status          string  `json:"status"`
	Messages        []byte  `json:"messages"`
	Model           *string `json:"model"`
	ClaimedAt       *int64  `json:"claimed_at"`
	LastHeartbeatAt *int64  `json:"last_heartbeat_at"`
	PendingMessage  *string `json:"pending_message"`
	EpicID          *string `json:"epic_id"`
	CreatedAt       int64   `json:"created_at"`
	UpdatedAt       int64   `json:"updated_at"`
}

type Epic struct {
	ID              string   `json:"id"`
	RepoID          string   `json:"repo_id"`
	Title           string   `json:"title"`
	Description     string   `json:"description"`
	Status          string   `json:"status"`
	ProposedTasks   []byte   `json:"proposed_tasks"`
	TaskIds         []string `json:"task_ids"`
	PlanningPrompt  *string  `json:"planning_prompt"`
	SessionLog      []string `json:"session_log"`
	NotReady        bool     `json:"not_ready"`
	ClaimedAt       *int64   `json:"claimed_at"`
	LastHeartbeatAt *int64   `json:"last_heartbeat_at"`
	Feedback        *string  `json:"feedback"`
	FeedbackType    *string  `json:"feedback_type"`
	Model           *string  `json:"model"`
	CreatedAt       int64    `json:"created_at"`
	UpdatedAt       int64    `json:"updated_at"`
	Number          *int32   `json:"number"`
}

type GithubToken struct {
	ID             string `json:"id"`
	EncryptedToken string `json:"encrypted_token"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type Repo struct {
	ID               string   `json:"id"`
	Owner            string   `json:"owner"`
	Name             string   `json:"name"`
	FullName         string   `json:"full_name"`
	CreatedAt        int64    `json:"created_at"`
	Summary          string   `json:"summary"`
	TechStack        []string `json:"tech_stack"`
	SetupStatus      string   `json:"setup_status"`
	HasCode          bool     `json:"has_code"`
	HasClaudeMd      bool     `json:"has_claude_md"`
	HasReadme        bool     `json:"has_readme"`
	Expectations     string   `json:"expectations"`
	SetupCompletedAt *int64   `json:"setup_completed_at"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

type Task struct {
	ID                     string     `json:"id"`
	RepoID                 string     `json:"repo_id"`
	Title                  string     `json:"title"`
	Description            string     `json:"description"`
	Status                 TaskStatus `json:"status"`
	PullRequestUrl         *string    `json:"pull_request_url"`
	PrNumber               *int32     `json:"pr_number"`
	DependsOn              []string   `json:"depends_on"`
	CloseReason            *string    `json:"close_reason"`
	Attempt                int32      `json:"attempt"`
	MaxAttempts            int32      `json:"max_attempts"`
	RetryReason            *string    `json:"retry_reason"`
	AcceptanceCriteriaList []string   `json:"acceptance_criteria_list"`
	AgentStatus            *string    `json:"agent_status"`
	RetryContext           *string    `json:"retry_context"`
	ConsecutiveFailures    int32      `json:"consecutive_failures"`
	CostUsd                float64    `json:"cost_usd"`
	MaxCostUsd             *float64   `json:"max_cost_usd"`
	SkipPr                 bool       `json:"skip_pr"`
	BranchName             *string    `json:"branch_name"`
	Model                  *string    `json:"model"`
	StartedAt              *int64     `json:"started_at"`
	Ready                  bool       `json:"ready"`
	LastHeartbeatAt        *int64     `json:"last_heartbeat_at"`
	EpicID                 *string    `json:"epic_id"`
	CreatedAt              int64      `json:"created_at"`
	UpdatedAt              int64      `json:"updated_at"`
	DraftPr                bool       `json:"draft_pr"`
	Type                   string     `json:"type"`
	Number                 *int32     `json:"number"`
}

type TaskLog struct {
	ID        int64    `json:"id"`
	TaskID    string   `json:"task_id"`
	Lines     []string `json:"lines"`
	Attempt   int32    `json:"attempt"`
	CreatedAt int64    `json:"created_at"`
}
