// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddTaskCost(ctx context.Context, arg AddTaskCostParams) error
	AppendConversationMessage(ctx context.Context, arg AppendConversationMessageParams) error
	AppendSessionLog(ctx context.Context, arg AppendSessionLogParams) error
	AppendTaskLogs(ctx context.Context, arg AppendTaskLogsParams) error
	AssignEpicNumber(ctx context.Context, arg AssignEpicNumberParams) (*int32, error)
	AssignTaskNumber(ctx context.Context, arg AssignTaskNumberParams) (*int32, error)
	BulkCloseTasksByEpic(ctx context.Context, arg BulkCloseTasksByEpicParams) error
	BulkDeleteTaskLogsByEpic(ctx context.Context, epicID *string) error
	BulkDeleteTaskLogsByIDs(ctx context.Context, dollar_1 []string) error
	BulkDeleteTasksByEpic(ctx context.Context, epicID *string) error
	BulkDeleteTasksByIDs(ctx context.Context, dollar_1 []string) error
	ClaimConversation(ctx context.Context, id string) (int64, error)
	ClaimEpic(ctx context.Context, id string) (int64, error)
	ClaimTask(ctx context.Context, id string) (int64, error)
	ClearEpicFeedback(ctx context.Context, id string) error
	ClearEpicIDForTasks(ctx context.Context, epicID *string) error
	CloseTask(ctx context.Context, arg CloseTaskParams) error
	ConversationHeartbeat(ctx context.Context, id string) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) error
	CreateEpic(ctx context.Context, arg CreateEpicParams) error
	CreateRepo(ctx context.Context, arg CreateRepoParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	DeleteConversation(ctx context.Context, id string) error
	DeleteEpic(ctx context.Context, id string) error
	DeleteExpiredLogs(ctx context.Context, createdAt int64) (int64, error)
	DeleteGitHubToken(ctx context.Context) error
	DeleteRepo(ctx context.Context, id string) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTask(ctx context.Context, id string) error
	DeleteTaskLogs(ctx context.Context, taskID string) error
	EpicHeartbeat(ctx context.Context, id string) error
	FeedbackRetryTask(ctx context.Context, arg FeedbackRetryTaskParams) (int64, error)
	HasTasksForRepo(ctx context.Context, repoID string) (bool, error)
	Heartbeat(ctx context.Context, id string) (int64, error)
	ListActiveConversations(ctx context.Context) ([]*Conversation, error)
	ListActiveEpics(ctx context.Context) ([]*Epic, error)
	ListConversationsByRepo(ctx context.Context, repoID string) ([]*Conversation, error)
	ListEpics(ctx context.Context) ([]*Epic, error)
	ListEpicsByRepo(ctx context.Context, repoID string) ([]*Epic, error)
	ListPendingConversations(ctx context.Context) ([]*Conversation, error)
	ListPendingTasks(ctx context.Context) ([]*Task, error)
	ListPendingTasksByRepos(ctx context.Context, dollar_1 []string) ([]*Task, error)
	ListPlanningEpics(ctx context.Context) ([]*Epic, error)
	ListRepos(ctx context.Context) ([]*Repo, error)
	ListReposBySetupStatus(ctx context.Context, setupStatus string) ([]*Repo, error)
	ListSettings(ctx context.Context) ([]*ListSettingsRow, error)
	ListStaleConversations(ctx context.Context, lastHeartbeatAt *int64) ([]*Conversation, error)
	ListStaleEpics(ctx context.Context, lastHeartbeatAt *int64) ([]*Epic, error)
	ListStaleTasks(ctx context.Context, lastHeartbeatAt *int64) ([]*Task, error)
	ListTasks(ctx context.Context) ([]*Task, error)
	ListTasksByEpic(ctx context.Context, epicID *string) ([]*Task, error)
	ListTasksByRepo(ctx context.Context, repoID string) ([]*Task, error)
	ListTasksInReview(ctx context.Context) ([]*Task, error)
	ListTasksInReviewByRepo(ctx context.Context, repoID string) ([]*Task, error)
	ListTasksInReviewNoPR(ctx context.Context) ([]*Task, error)
	ManualRetryTask(ctx context.Context, arg ManualRetryTaskParams) (int64, error)
	ReadConversation(ctx context.Context, id string) (*Conversation, error)
	ReadEpic(ctx context.Context, id string) (*Epic, error)
	ReadEpicByNumber(ctx context.Context, arg ReadEpicByNumberParams) (*Epic, error)
	ReadGitHubToken(ctx context.Context) (string, error)
	ReadRepo(ctx context.Context, id string) (*Repo, error)
	ReadRepoByFullName(ctx context.Context, fullName string) (*Repo, error)
	ReadSetting(ctx context.Context, key string) (string, error)
	ReadTask(ctx context.Context, id string) (*Task, error)
	ReadTaskByNumber(ctx context.Context, arg ReadTaskByNumberParams) (*Task, error)
	ReadTaskLogs(ctx context.Context, id string) ([]*ReadTaskLogsRow, error)
	ReadTaskStatus(ctx context.Context, id string) (TaskStatus, error)
	ReleaseConversationClaim(ctx context.Context, id string) error
	ReleaseEpicClaim(ctx context.Context, id string) error
	RemoveDependency(ctx context.Context, arg RemoveDependencyParams) error
	RemoveEpicTaskID(ctx context.Context, arg RemoveEpicTaskIDParams) error
	RetryTask(ctx context.Context, arg RetryTaskParams) (int64, error)
	ScheduleRetryFromRunning(ctx context.Context, arg ScheduleRetryFromRunningParams) (int64, error)
	SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) error
	SetBranchName(ctx context.Context, arg SetBranchNameParams) error
	SetCloseReason(ctx context.Context, arg SetCloseReasonParams) error
	SetConsecutiveFailures(ctx context.Context, arg SetConsecutiveFailuresParams) error
	SetConversationEpicID(ctx context.Context, arg SetConversationEpicIDParams) error
	SetConversationMessages(ctx context.Context, arg SetConversationMessagesParams) error
	SetEpicFeedback(ctx context.Context, arg SetEpicFeedbackParams) error
	SetEpicTaskIDs(ctx context.Context, arg SetEpicTaskIDsParams) error
	SetPendingMessage(ctx context.Context, arg SetPendingMessageParams) error
	SetReady(ctx context.Context, arg SetReadyParams) error
	SetRetryContext(ctx context.Context, arg SetRetryContextParams) error
	SetTaskPullRequest(ctx context.Context, arg SetTaskPullRequestParams) error
	StartOverTask(ctx context.Context, arg StartOverTaskParams) (int64, error)
	StopTask(ctx context.Context, arg StopTaskParams) (int64, error)
	TaskExists(ctx context.Context, id string) (bool, error)
	UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error
	UpdateEpic(ctx context.Context, arg UpdateEpicParams) error
	UpdateEpicStatus(ctx context.Context, arg UpdateEpicStatusParams) error
	UpdatePendingTask(ctx context.Context, arg UpdatePendingTaskParams) (int64, error)
	UpdateProposedTasks(ctx context.Context, arg UpdateProposedTasksParams) error
	UpdateRepoExpectations(ctx context.Context, arg UpdateRepoExpectationsParams) error
	UpdateRepoSetupScan(ctx context.Context, arg UpdateRepoSetupScanParams) error
	UpdateRepoSetupStatus(ctx context.Context, arg UpdateRepoSetupStatusParams) error
	UpdateRepoSummary(ctx context.Context, arg UpdateRepoSummaryParams) error
	UpdateRepoTechStack(ctx context.Context, arg UpdateRepoTechStackParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpsertGitHubToken(ctx context.Context, arg UpsertGitHubTokenParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
