// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo.sql

package sqlc

import (
	"context"
)

const createRepo = `-- name: CreateRepo :exec
INSERT INTO repo (id, owner, name, full_name, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRepoParams struct {
	ID        string `json:"id"`
	Owner     string `json:"owner"`
	Name      string `json:"name"`
	FullName  string `json:"full_name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) error {
	_, err := q.db.Exec(ctx, createRepo,
		arg.ID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.CreatedAt,
	)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repo WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const listRepos = `-- name: ListRepos :many
SELECT id, owner, name, full_name, created_at FROM repo ORDER BY created_at DESC
`

func (q *Queries) ListRepos(ctx context.Context) ([]*Repo, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRepo = `-- name: ReadRepo :one
SELECT id, owner, name, full_name, created_at FROM repo WHERE id = $1
`

func (q *Queries) ReadRepo(ctx context.Context, id string) (*Repo, error) {
	row := q.db.QueryRow(ctx, readRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.CreatedAt,
	)
	return &i, err
}

const readRepoByFullName = `-- name: ReadRepoByFullName :one
SELECT id, owner, name, full_name, created_at FROM repo WHERE full_name = $1
`

func (q *Queries) ReadRepoByFullName(ctx context.Context, fullName string) (*Repo, error) {
	row := q.db.QueryRow(ctx, readRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.CreatedAt,
	)
	return &i, err
}
