// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package sqlc

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM setting WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM setting
`

type ListSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListSettings(ctx context.Context) ([]*ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListSettingsRow
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSetting = `-- name: ReadSetting :one
SELECT value FROM setting WHERE key = $1
`

func (q *Queries) ReadSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, readSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO setting (key, value, updated_at) VALUES ($1, $2, EXTRACT(EPOCH FROM NOW())::BIGINT)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
