// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"
)

const addTaskCost = `-- name: AddTaskCost :exec
UPDATE task SET cost_usd = cost_usd + $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type AddTaskCostParams struct {
	ID      string  `json:"id"`
	CostUsd float64 `json:"cost_usd"`
}

func (q *Queries) AddTaskCost(ctx context.Context, arg AddTaskCostParams) error {
	_, err := q.db.Exec(ctx, addTaskCost, arg.ID, arg.CostUsd)
	return err
}

const appendTaskLogs = `-- name: AppendTaskLogs :exec
INSERT INTO task_log (task_id, attempt, lines) VALUES ($1, $2, $3)
`

type AppendTaskLogsParams struct {
	ID      string   `json:"id"`
	Attempt int32    `json:"attempt"`
	Lines   []string `json:"lines"`
}

func (q *Queries) AppendTaskLogs(ctx context.Context, arg AppendTaskLogsParams) error {
	_, err := q.db.Exec(ctx, appendTaskLogs, arg.ID, arg.Attempt, arg.Lines)
	return err
}

const bulkCloseTasksByEpic = `-- name: BulkCloseTasksByEpic :exec
UPDATE task SET status = 'closed', close_reason = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE epic_id = $1 AND status NOT IN ('closed', 'merged')
`

type BulkCloseTasksByEpicParams struct {
	EpicID      *string `json:"epic_id"`
	CloseReason *string `json:"close_reason"`
}

func (q *Queries) BulkCloseTasksByEpic(ctx context.Context, arg BulkCloseTasksByEpicParams) error {
	_, err := q.db.Exec(ctx, bulkCloseTasksByEpic, arg.EpicID, arg.CloseReason)
	return err
}

const bulkDeleteTaskLogsByEpic = `-- name: BulkDeleteTaskLogsByEpic :exec
DELETE FROM task_log WHERE task_id IN (SELECT id FROM task WHERE epic_id = $1)
`

func (q *Queries) BulkDeleteTaskLogsByEpic(ctx context.Context, epicID *string) error {
	_, err := q.db.Exec(ctx, bulkDeleteTaskLogsByEpic, epicID)
	return err
}

const bulkDeleteTaskLogsByIDs = `-- name: BulkDeleteTaskLogsByIDs :exec
DELETE FROM task_log WHERE task_id = ANY($1::text[])
`

func (q *Queries) BulkDeleteTaskLogsByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, bulkDeleteTaskLogsByIDs, dollar_1)
	return err
}

const bulkDeleteTasksByEpic = `-- name: BulkDeleteTasksByEpic :exec
DELETE FROM task WHERE epic_id = $1
`

func (q *Queries) BulkDeleteTasksByEpic(ctx context.Context, epicID *string) error {
	_, err := q.db.Exec(ctx, bulkDeleteTasksByEpic, epicID)
	return err
}

const bulkDeleteTasksByIDs = `-- name: BulkDeleteTasksByIDs :exec
DELETE FROM task WHERE id = ANY($1::text[])
`

func (q *Queries) BulkDeleteTasksByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, bulkDeleteTasksByIDs, dollar_1)
	return err
}

const claimTask = `-- name: ClaimTask :execrows
UPDATE task SET status = 'running', started_at = EXTRACT(EPOCH FROM NOW())::BIGINT, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'pending' AND ready = true
`

func (q *Queries) ClaimTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, claimTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearEpicIDForTasks = `-- name: ClearEpicIDForTasks :exec
UPDATE task SET epic_id = NULL, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE epic_id = $1
`

func (q *Queries) ClearEpicIDForTasks(ctx context.Context, epicID *string) error {
	_, err := q.db.Exec(ctx, clearEpicIDForTasks, epicID)
	return err
}

const closeTask = `-- name: CloseTask :exec
UPDATE task SET status = 'closed', close_reason = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type CloseTaskParams struct {
	ID          string  `json:"id"`
	CloseReason *string `json:"close_reason"`
}

func (q *Queries) CloseTask(ctx context.Context, arg CloseTaskParams) error {
	_, err := q.db.Exec(ctx, closeTask, arg.ID, arg.CloseReason)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO task (id, repo_id, title, description, status, depends_on, attempt, max_attempts, acceptance_criteria_list, max_cost_usd, skip_pr, model, ready, epic_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type CreateTaskParams struct {
	ID                     string     `json:"id"`
	RepoID                 string     `json:"repo_id"`
	Title                  string     `json:"title"`
	Description            string     `json:"description"`
	Status                 TaskStatus `json:"status"`
	DependsOn              []string   `json:"depends_on"`
	Attempt                int32      `json:"attempt"`
	MaxAttempts            int32      `json:"max_attempts"`
	AcceptanceCriteriaList []string   `json:"acceptance_criteria_list"`
	MaxCostUsd             *float64   `json:"max_cost_usd"`
	SkipPr                 bool       `json:"skip_pr"`
	Model                  *string    `json:"model"`
	Ready                  bool       `json:"ready"`
	EpicID                 *string    `json:"epic_id"`
	CreatedAt              int64      `json:"created_at"`
	UpdatedAt              int64      `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.RepoID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.DependsOn,
		arg.Attempt,
		arg.MaxAttempts,
		arg.AcceptanceCriteriaList,
		arg.MaxCostUsd,
		arg.SkipPr,
		arg.Model,
		arg.Ready,
		arg.EpicID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredLogs = `-- name: DeleteExpiredLogs :execrows
DELETE FROM task_log WHERE created_at < $1
`

func (q *Queries) DeleteExpiredLogs(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLogs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteTaskLogs = `-- name: DeleteTaskLogs :exec
DELETE FROM task_log WHERE task_id = $1
`

func (q *Queries) DeleteTaskLogs(ctx context.Context, taskID string) error {
	_, err := q.db.Exec(ctx, deleteTaskLogs, taskID)
	return err
}

const feedbackRetryTask = `-- name: FeedbackRetryTask :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1,
  max_attempts = max_attempts + 1,
  retry_reason = $2, retry_context = NULL,
  consecutive_failures = 0,
  started_at = NULL, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'review'
`

type FeedbackRetryTaskParams struct {
	ID          string  `json:"id"`
	RetryReason *string `json:"retry_reason"`
}

func (q *Queries) FeedbackRetryTask(ctx context.Context, arg FeedbackRetryTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, feedbackRetryTask, arg.ID, arg.RetryReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasTasksForRepo = `-- name: HasTasksForRepo :one
SELECT EXISTS(SELECT 1 FROM task WHERE repo_id = $1)
`

func (q *Queries) HasTasksForRepo(ctx context.Context, repoID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasTasksForRepo, repoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heartbeat = `-- name: Heartbeat :execrows
UPDATE task SET last_heartbeat_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1 AND status = 'running'
`

func (q *Queries) Heartbeat(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'pending' AND ready = true ORDER BY created_at ASC
`

func (q *Queries) ListPendingTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasksByRepos = `-- name: ListPendingTasksByRepos :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'pending' AND ready = true AND repo_id = ANY($1::text[]) ORDER BY created_at ASC
`

func (q *Queries) ListPendingTasksByRepos(ctx context.Context, dollar_1 []string) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listPendingTasksByRepos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleTasks = `-- name: ListStaleTasks :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'running' AND last_heartbeat_at IS NOT NULL AND last_heartbeat_at < $1 ORDER BY started_at
`

func (q *Queries) ListStaleTasks(ctx context.Context, lastHeartbeatAt *int64) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listStaleTasks, lastHeartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByEpic = `-- name: ListTasksByEpic :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE epic_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTasksByEpic(ctx context.Context, epicID *string) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasksByEpic, epicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByRepo = `-- name: ListTasksByRepo :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE repo_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTasksByRepo(ctx context.Context, repoID string) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasksByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInReview = `-- name: ListTasksInReview :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'review'
`

func (q *Queries) ListTasksInReview(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasksInReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInReviewByRepo = `-- name: ListTasksInReviewByRepo :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE repo_id = $1 AND status = 'review'
`

func (q *Queries) ListTasksInReviewByRepo(ctx context.Context, repoID string) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasksInReviewByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksInReviewNoPR = `-- name: ListTasksInReviewNoPR :many
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE status = 'review' AND branch_name IS NOT NULL AND pr_number IS NULL
`

func (q *Queries) ListTasksInReviewNoPR(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasksInReviewNoPR)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.PullRequestUrl,
			&i.PrNumber,
			&i.DependsOn,
			&i.CloseReason,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RetryReason,
			&i.AcceptanceCriteriaList,
			&i.AgentStatus,
			&i.RetryContext,
			&i.ConsecutiveFailures,
			&i.CostUsd,
			&i.MaxCostUsd,
			&i.SkipPr,
			&i.BranchName,
			&i.Model,
			&i.StartedAt,
			&i.Ready,
			&i.LastHeartbeatAt,
			&i.EpicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manualRetryTask = `-- name: ManualRetryTask :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1,
  retry_reason = $2, retry_context = NULL,
  close_reason = NULL, consecutive_failures = 0,
  started_at = NULL, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'failed'
`

type ManualRetryTaskParams struct {
	ID          string  `json:"id"`
	RetryReason *string `json:"retry_reason"`
}

func (q *Queries) ManualRetryTask(ctx context.Context, arg ManualRetryTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, manualRetryTask, arg.ID, arg.RetryReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readTask = `-- name: ReadTask :one
SELECT id, repo_id, title, description, status, pull_request_url, pr_number, depends_on, close_reason, attempt, max_attempts, retry_reason, acceptance_criteria_list, agent_status, retry_context, consecutive_failures, cost_usd, max_cost_usd, skip_pr, branch_name, model, started_at, ready, last_heartbeat_at, epic_id, created_at, updated_at FROM task WHERE id = $1
`

func (q *Queries) ReadTask(ctx context.Context, id string) (*Task, error) {
	row := q.db.QueryRow(ctx, readTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.PullRequestUrl,
		&i.PrNumber,
		&i.DependsOn,
		&i.CloseReason,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryReason,
		&i.AcceptanceCriteriaList,
		&i.AgentStatus,
		&i.RetryContext,
		&i.ConsecutiveFailures,
		&i.CostUsd,
		&i.MaxCostUsd,
		&i.SkipPr,
		&i.BranchName,
		&i.Model,
		&i.StartedAt,
		&i.Ready,
		&i.LastHeartbeatAt,
		&i.EpicID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const readTaskLogs = `-- name: ReadTaskLogs :many
SELECT attempt, lines FROM task_log WHERE task_id = $1 ORDER BY id
`

type ReadTaskLogsRow struct {
	Attempt int32    `json:"attempt"`
	Lines   []string `json:"lines"`
}

func (q *Queries) ReadTaskLogs(ctx context.Context, id string) ([]*ReadTaskLogsRow, error) {
	rows, err := q.db.Query(ctx, readTaskLogs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReadTaskLogsRow
	for rows.Next() {
		var i ReadTaskLogsRow
		if err := rows.Scan(&i.Attempt, &i.Lines); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readTaskStatus = `-- name: ReadTaskStatus :one
SELECT status FROM task WHERE id = $1
`

func (q *Queries) ReadTaskStatus(ctx context.Context, id string) (TaskStatus, error) {
	row := q.db.QueryRow(ctx, readTaskStatus, id)
	var status TaskStatus
	err := row.Scan(&status)
	return status, err
}

const removeDependency = `-- name: RemoveDependency :exec
UPDATE task SET depends_on = array_remove(depends_on, $2), updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type RemoveDependencyParams struct {
	ID          string      `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) RemoveDependency(ctx context.Context, arg RemoveDependencyParams) error {
	_, err := q.db.Exec(ctx, removeDependency, arg.ID, arg.ArrayRemove)
	return err
}

const retryTask = `-- name: RetryTask :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1, retry_reason = $2, started_at = NULL, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'review'
`

type RetryTaskParams struct {
	ID          string  `json:"id"`
	RetryReason *string `json:"retry_reason"`
}

func (q *Queries) RetryTask(ctx context.Context, arg RetryTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryTask, arg.ID, arg.RetryReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleRetryFromRunning = `-- name: ScheduleRetryFromRunning :execrows
UPDATE task SET status = 'pending', attempt = attempt + 1, retry_reason = $2, started_at = NULL, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'running'
`

type ScheduleRetryFromRunningParams struct {
	ID          string  `json:"id"`
	RetryReason *string `json:"retry_reason"`
}

func (q *Queries) ScheduleRetryFromRunning(ctx context.Context, arg ScheduleRetryFromRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleRetryFromRunning, arg.ID, arg.RetryReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAgentStatus = `-- name: SetAgentStatus :exec
UPDATE task SET agent_status = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type SetAgentStatusParams struct {
	ID          string  `json:"id"`
	AgentStatus *string `json:"agent_status"`
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) error {
	_, err := q.db.Exec(ctx, setAgentStatus, arg.ID, arg.AgentStatus)
	return err
}

const setBranchName = `-- name: SetBranchName :exec
UPDATE task SET branch_name = $2, status = 'review', updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type SetBranchNameParams struct {
	ID         string  `json:"id"`
	BranchName *string `json:"branch_name"`
}

func (q *Queries) SetBranchName(ctx context.Context, arg SetBranchNameParams) error {
	_, err := q.db.Exec(ctx, setBranchName, arg.ID, arg.BranchName)
	return err
}

const setCloseReason = `-- name: SetCloseReason :exec
UPDATE task SET close_reason = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type SetCloseReasonParams struct {
	ID          string  `json:"id"`
	CloseReason *string `json:"close_reason"`
}

func (q *Queries) SetCloseReason(ctx context.Context, arg SetCloseReasonParams) error {
	_, err := q.db.Exec(ctx, setCloseReason, arg.ID, arg.CloseReason)
	return err
}

const setConsecutiveFailures = `-- name: SetConsecutiveFailures :exec
UPDATE task SET consecutive_failures = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type SetConsecutiveFailuresParams struct {
	ID                  string `json:"id"`
	ConsecutiveFailures int32  `json:"consecutive_failures"`
}

func (q *Queries) SetConsecutiveFailures(ctx context.Context, arg SetConsecutiveFailuresParams) error {
	_, err := q.db.Exec(ctx, setConsecutiveFailures, arg.ID, arg.ConsecutiveFailures)
	return err
}

const setReady = `-- name: SetReady :exec
UPDATE task SET ready = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type SetReadyParams struct {
	ID    string `json:"id"`
	Ready bool   `json:"ready"`
}

func (q *Queries) SetReady(ctx context.Context, arg SetReadyParams) error {
	_, err := q.db.Exec(ctx, setReady, arg.ID, arg.Ready)
	return err
}

const setRetryContext = `-- name: SetRetryContext :exec
UPDATE task SET retry_context = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT WHERE id = $1
`

type SetRetryContextParams struct {
	ID           string  `json:"id"`
	RetryContext *string `json:"retry_context"`
}

func (q *Queries) SetRetryContext(ctx context.Context, arg SetRetryContextParams) error {
	_, err := q.db.Exec(ctx, setRetryContext, arg.ID, arg.RetryContext)
	return err
}

const setTaskPullRequest = `-- name: SetTaskPullRequest :exec
UPDATE task SET pull_request_url = $2, pr_number = $3, status = 'review', updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type SetTaskPullRequestParams struct {
	ID             string  `json:"id"`
	PullRequestUrl *string `json:"pull_request_url"`
	PrNumber       *int32  `json:"pr_number"`
}

func (q *Queries) SetTaskPullRequest(ctx context.Context, arg SetTaskPullRequestParams) error {
	_, err := q.db.Exec(ctx, setTaskPullRequest, arg.ID, arg.PullRequestUrl, arg.PrNumber)
	return err
}

const startOverTask = `-- name: StartOverTask :execrows
UPDATE task SET
  status = 'pending',
  title = $2,
  description = $3,
  acceptance_criteria_list = $4,
  attempt = 1,
  max_attempts = 5,
  retry_reason = NULL,
  retry_context = NULL,
  close_reason = NULL,
  agent_status = NULL,
  consecutive_failures = 0,
  cost_usd = 0,
  pull_request_url = NULL,
  pr_number = NULL,
  branch_name = NULL,
  started_at = NULL,
  updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status IN ('review', 'failed', 'closed')
`

type StartOverTaskParams struct {
	ID                     string   `json:"id"`
	Title                  string   `json:"title"`
	Description            string   `json:"description"`
	AcceptanceCriteriaList []string `json:"acceptance_criteria_list"`
}

func (q *Queries) StartOverTask(ctx context.Context, arg StartOverTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, startOverTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AcceptanceCriteriaList,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopTask = `-- name: StopTask :execrows
UPDATE task SET status = 'pending', ready = false, close_reason = $2,
  started_at = NULL, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'running'
`

type StopTaskParams struct {
	ID          string  `json:"id"`
	CloseReason *string `json:"close_reason"`
}

func (q *Queries) StopTask(ctx context.Context, arg StopTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopTask, arg.ID, arg.CloseReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS(SELECT 1 FROM task WHERE id = $1)
`

func (q *Queries) TaskExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, taskExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePendingTask = `-- name: UpdatePendingTask :execrows
UPDATE task SET
  title = $2,
  description = $3,
  depends_on = $4,
  acceptance_criteria_list = $5,
  max_cost_usd = $6,
  skip_pr = $7,
  model = $8,
  ready = $9,
  updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1 AND status = 'pending'
`

type UpdatePendingTaskParams struct {
	ID                     string   `json:"id"`
	Title                  string   `json:"title"`
	Description            string   `json:"description"`
	DependsOn              []string `json:"depends_on"`
	AcceptanceCriteriaList []string `json:"acceptance_criteria_list"`
	MaxCostUsd             *float64 `json:"max_cost_usd"`
	SkipPr                 bool     `json:"skip_pr"`
	Model                  *string  `json:"model"`
	Ready                  bool     `json:"ready"`
}

func (q *Queries) UpdatePendingTask(ctx context.Context, arg UpdatePendingTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePendingTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DependsOn,
		arg.AcceptanceCriteriaList,
		arg.MaxCostUsd,
		arg.SkipPr,
		arg.Model,
		arg.Ready,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task SET status = $2, updated_at = EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     string     `json:"id"`
	Status TaskStatus `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
